---
- name: Display File Information or List Files
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Display List of Files in a Path
      ansible.builtin.shell: "whoami"
      register: files_list
    - name: Display List of Files
      debug:
        var: files_list.stdout_lines
