---
- name: Fetch Logon Information and Send Email
  hosts: all
  gather_facts: false
  tasks:
    - name: Get Logon Information
      ansible.builtin.win_shell: |
        $startDate = (Get-Date).AddDays(-30)
        $excludedUsers = @('DWM', 'LOCAL SERVICE', 'NETWORK SERVICE', 'SYSTEM', 'UMFD')
        
        $loginInfo = Get-WinEvent -FilterHashtable @{
            LogName='Security';
            Id=4624;
            StartTime=$startDate
        } | Where-Object { 
            ($_.Properties[8].Value -eq 2 -or $_.Properties[8].Value -eq 10) -and
            $_.Properties[5].Value -notmatch "($([string]::Join('|', $excludedUsers)))"
        } | Select-Object @{
            Name='Login-Date'; Expression={$_.TimeCreated.ToString("yyyy-MM-dd")}
        }, @{
            Name='Login-Time'; Expression={$_.TimeCreated.ToString("HH:mm:ss")}
        }, MachineName, @{
            Name='User'; Expression={$_.Properties[5].Value}
        }, @{
            Name='LogonType'; Expression={
                switch ($_.Properties[8].Value) {
                    2 { 'LocalInteractive' }
                    3 { 'Network' }
                    4 { 'Batch' }
                    5 { 'Service' }
                    7 { 'Unlock' }
                    8 { 'NetworkCleartext' }
                    9 { 'NewCredentials' }
                    10 { 'RemoteInteractive' }
                    11 { 'CachedInteractive' }
                    default { $_.Properties[8].Value }
                }
            }
        }, @{
            Name='Source-IP'; Expression={$_.Properties[18].Value}
        }
        $loginInfo | Format-Table # | Export-Csv -Path C:\path\to\output.csv -NoTypeInformation
      
      register: result  
                
- name: Display result to Console
  hosts: localhost
  tasks:
    - name: save output to file
      ansible.builtin.shell:
        debug:
          var: result.stdout_lines >> userlogin.txt
             
    - name: Display List of Files in a Path
      ansible.builtin.shell: "ls -lrt"
      register: files_list
    - name: Display List of Files
      debug:
        var: files_list.stdout_lines
